name: Check

on:
  workflow_call:
  pull_request:
    branches:
      - master

env:
  HUSKY: 0

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com
          node-version: 18
          cache: npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FINANDO_GITHUB_BOT_TOKEN }}

      - name: Install dependencies
        run: npm ci --quiet --ignore-scripts

      - name: Audit dependencies
        run: npm audit --omit=dev --audit-level=moderate

      - name: Build project
        run: npm run build

      - name: Lint project
        run: npm run lint

      - name: Test project
        run: npm run test
