name: Deploy to AWS S3 bucket

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version:
        required: false
        type: string
      region:
        required: false
        type: string
        default: eu-west-1
    secrets:
      FINANDO_GITHUB_BOT_TOKEN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  HUSKY: 0

jobs:
  deploy-to-aws-s3-bucket:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com
          node-version: 18
          cache: npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FINANDO_GITHUB_BOT_TOKEN }}

      - name: Install dependencies
        run: npm ci --quiet --ignore-scripts

      - name: Build
        run: npm run build:prod

      - name: Install envsubst
        run: |
          sudo apt-get update
          sudo apt-get install gettext-base

      - name: Create configuration
        env:
          ENV: ${{ inputs.environment }}
          GRAPHQL_ENDPOINT: ${{ vars.GRAPHQL_ENDPOINT }}
          TRANSLATIONS_DOCUMENT: ${{ vars.TRANSLATIONS_DOCUMENT }}
          AUTH_REST_API_HOST: ${{ vars.AUTH_REST_API_HOST }}
        run: envsubst < ./config.template > ./dist/config.js;

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}

      - name: Deploy static content to AWS S3 bucket
        run: aws s3 sync dist s3://${{ vars.AWS_S3_BUCKET_NAME }} --delete
